sudo: false
language: node_js
node_js:
  - '0.8'
  - '0.10'
  - '0.12'
  - '4'
  - '6'
  - '8'
  - '10'
matrix:
  fast_finish: true
  allow_failures:
    - node_js: '0.8'
cache:
  directories:
    - '$HOME/.npm'
    - '$HOME/.yarn-cache'
install:
  - eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/a16fffacc146944edb58d02bbc565bf467099b18/scripts/node-install.bash)"
before_script:
  - eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/a16fffacc146944edb58d02bbc565bf467099b18/scripts/node-verify.bash)"
after_success:
  - eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/a16fffacc146944edb58d02bbc565bf467099b18/scripts/surge.bash)"
  - eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/a16fffacc146944edb58d02bbc565bf467099b18/scripts/node-publish.bash)"
notifications:
  email:
    recipients:
      secure: xL2WoUlG4/6PsktJDbG3tXLl6pkPIeeYax6A3WDckzQzZNwigWn1CShyOzlSFnGbkkGVMo6R2Mmc3enTl+bhPvGasdqk3RElDCAzxPgKtxfuCab7DgEL40YW0E2v5ZNbJJkIGmNeCRHu2QatD/BBehZ1dd4qujh+tARYlyMokfnPfPM3FbegwaST9yHGR4sv7370Ig2D/Hwxs0AUtt+Wi8Y/j9KI6d819NA92C8IWAdnSHPLsoFV679QKCWP5lRXkvu8S3OMYzLa7oawGpalcgJKYtqUKH6NsUvw2geDBH8q64pzmxsHhA3NUc+gDcMkm8vSCWOWC6Yeovv7roZ1+c5ONg/cgQWGBpgJ10jY4UidUM0wLvEGMKgyQ0/W1+hMQ0BklJ+hFJrPxrIpb01hwXLYITj/PupW6zmY+7l8iMkBcRn/JjhTqE6vZe1spDsKc+KiI2VwFtBMgmrWjt4K8ExtK01ekS5320g2fetWlFq5/uW0nq4emcFtRgVPVrw2XvNAILJAkiPuokRHkZh6lzxauG/p8euBvEiDaQ2mWIsXkPCPhlNAO3f3+IYYh02ZhR+ZoEFDgDdj6KS2fOFOVKqOHKTiRqb/+cExFYv6YMhr0zoB+jtP/uA0Dfu77J+B5LWuI1Ao7Jg8BH+ejUM9JywgNeNmEuCQJaH7CfhPg+A=
